### DISCUSSION TITLE
what is the checked grid background?

### DISCUSSION THREAD

**Discussion by kumawatdarshan** [ekmas/neobrutalism-components#82] [Q&A] [answered]
Is this manual css or there is some name for it as i see it being used everywhere.

![image](https://github.com/user-attachments/assets/f5552ed8-6e3c-459c-83cf-c4cae3372133)
![image](https://github.com/user-attachments/assets/4db63545-1bd8-43b4-baef-f07c0aaac2ac)

**Comment by flandia** [comment, marked as answer]
I checked the repo, and it appears that it is created by custom tailwind utilities.

I created utilities to quickly apply these styles (adapted from this codebase):

```css
@utility bg-lattice {
    background-color: var(--background);
    background-image: linear-gradient(to right, #80808033 1px, transparent 1px), linear-gradient(to bottom, #80808033 1px, transparent 1px);
    background-size: 30px 30px;
}

@utility bg-secondary-lattice {
    background-color: var(--secondary-background);
    background-image: linear-gradient(to right, #80808033 1px, transparent 1px), linear-gradient(to bottom, #80808033 1px, transparent 1px);
    background-size: 30px 30px;
}
```
